version: '3.3'

volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: rybakovilya/yamdb:v1.1
    restart: always
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.0
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web